name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux-appimage:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          python3-pip \
          python3-venv \
          pandoc \
          poppler-utils \
          libgtk-3-0 \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          imagemagick \
          wget \
          fuse \
          file
          
    - name: Create virtual environment and install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Download AppImage tools
      run: |
        cd build
        if [ ! -f appimagetool ]; then
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          sudo mv appimagetool-x86_64.AppImage /usr/local/bin/appimagetool
        fi
        
    - name: Build AppImage
      run: |
        cd build
        chmod +x create-appimage.sh
        ./create-appimage.sh
        
    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux-appimage
        path: build/Hiel-PDF-Converter-*.AppImage

  build-windows-exe:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build Windows executable
      run: |
        pyinstaller --name "Hiel-PDF-Converter" ^
          --onefile ^
          --windowed ^
          --icon "assets/hiel-converter.png" ^
          --add-data "assets;assets" ^
          --add-data "config;config" ^
          --add-data "domain;domain" ^
          --add-data "infrastructure;infrastructure" ^
          --add-data "presentation;presentation" ^
          --add-data "use_cases;use_cases" ^
          --hidden-import "flet" ^
          --hidden-import "flet.core" ^
          --hidden-import "pdf2image" ^
          --hidden-import "pypdf" ^
          --hidden-import "pypandoc" ^
          --hidden-import "docx" ^
          --hidden-import "PIL" ^
          --hidden-import "reportlab" ^
          main.py
          
    - name: Upload Windows executable artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/Hiel-PDF-Converter.exe

  create-release:
    needs: [build-linux-appimage, build-windows-exe]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Linux AppImage
      uses: actions/download-artifact@v3
      with:
        name: linux-appimage
        path: ./artifacts/
        
    - name: Download Windows executable
      uses: actions/download-artifact@v3
      with:
        name: windows-exe
        path: ./artifacts/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/Hiel-PDF-Converter-*.AppImage
          artifacts/Hiel-PDF-Converter.exe
        name: Release ${{ github.ref_name }}
        body: |
          ## Hiel PDF Converter ${{ github.ref_name }}
          
          ### Downloads
          - **Linux**: `Hiel-PDF-Converter-*.AppImage` - Portable AppImage for all Linux distributions
          - **Windows**: `Hiel-PDF-Converter.exe` - Standalone executable for Windows
          
          ### Features
          - Convert PDF files to text, Word, HTML, Markdown, and images
          - Advanced image quality control with custom DPI settings
          - Modern scrollable UI with quality presets
          - Size optimization up to 97% compression
          - Self-contained with all dependencies included
          
          ### System Requirements
          - **Linux**: x86_64, any modern distribution
          - **Windows**: Windows 10 or later
          
          ### Usage
          - **Linux**: `chmod +x Hiel-PDF-Converter-*.AppImage && ./Hiel-PDF-Converter-*.AppImage`
          - **Windows**: Double-click `Hiel-PDF-Converter.exe`
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}